apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autoscillab-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-vault
    kind: ClusterSecretStore
  target:
    name: autoscillab-secrets
    creationPolicy: Owner
  data:
{{- range $key, $path := .Values.secrets.externalSecrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $path }}
{{- end }}
