
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscillab-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscillab-api
  template:
    metadata:
      labels:
        app: autoscillab-api
    spec:
      containers:
        - name: api
          image: autoscillab/api:latest
          ports:
            - containerPort: 8000
