apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autoscillab-rotating-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: my-vault
    kind: ClusterSecretStore
  target:
    name: autoscillab-rotating
    creationPolicy: Owner
  data:
    - secretKey: PINECONE_API_KEY
      remoteRef:
        key: /autoscillab/pinecone/api_key
    - secretKey: JWT_SECRET
      remoteRef:
        key: /autoscillab/jwt/secret
