apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autoscillab-secret-reader
  namespace: autoscillab
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autoscillab-secret-reader-binding
  namespace: autoscillab
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: autoscillab-secret-reader
  apiGroup: rbac.authorization.k8s.io
