
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscillab-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscillab-worker
  template:
    metadata:
      labels:
        app: autoscillab-worker
    spec:
      containers:
        - name: worker
          image: autoscillab/worker:latest
